version: '3.5'

services:
  alchemy_api:
    container_name: alchemy_api
    image: alchemyc
    volumes:
       - ./.env:/app/.env
       - ./postgre.json:/app/connection_to_postgre/postgre.json
       - ./reinitialize_super_user.json:/app/reinitialize_super_user.json
       - ./postgre_initialized.json:/app/connection_to_postgre/postgre_initialized.json
       - ./.env.nginx:/app/.env.nginx
       - ./.env.sentiment:/app/.env.sentiment
       - ./ca.crt:/app/ca.crt
       - ./ca.key:/app./ca.key
    ports:
      - "3201:91"
    networks:
      - alchemy
    restart: unless-stopped


networks:
  alchemy:
    driver: bridge
